football < football.judge.01.in > football.judge.01.out
football < football.judge.02.in > football.judge.02.out
football < football.judge.03.in > football.judge.03.out
football < football.judge.04.in > football.judge.04.out
football < football.judge.05.in > football.judge.05.out
football < football.judge.06.in > football.judge.06.out
football < football.judge.07.in > football.judge.07.out
football < football.judge.08.in > football.judge.08.out
football < football.judge.09.in > football.judge.09.out
football < football.judge.10.in > football.judge.10.out
football < football.judge.11.in > football.judge.11.out
football < football.judge.12.in > football.judge.12.out
football < football.judge.13.in > football.judge.13.out
football < football.judge.14.in > football.judge.14.out
football < football.judge.15.in > football.judge.15.out
football < football.judge.16.in > football.judge.16.out
football < football.judge.17.in > football.judge.17.out
football < football.judge.18.in > football.judge.18.out
football < football.judge.19.in > football.judge.19.out
football < football.judge.20.in > football.judge.20.out
football < football.judge.21.in > football.judge.21.out
football < football.judge.22.in > football.judge.22.out
football < football.judge.23.in > football.judge.23.out
football < football.judge.24.in > football.judge.24.out
football < football.judge.25.in > football.judge.25.out
